version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    container_name: elasticsearch
    hostname: elasticsearch
    networks:
      - "stack"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata0:/usr/share/elasticsearch/data
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.3"
    container_name: kibana
    hostname: kibana
    networks:
      - "stack"
    depends_on: ['elasticsearch']
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"

  logstash:
    image: "docker.elastic.co/logstash/logstash:6.2.3"
    container_name: logstash
    hostname: logstash
    networks:
      - "stack"
    depends_on: ['elasticsearch']
    links:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
     - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5

networks: {stack: {}}

volumes:
  esdata0:
    driver: local